version: '3.2'

services:
  wordpress:
    image: wordpress:5.7-fpm-alpine
    user: "33"
    restart: always
    env_file:
      - ./wordpress/wordpress.env
    #environment:
      #WORDPRESS_CONFIG_EXTRA: |
        #define('RT_WP_NGINX_HELPER_CACHE_PATH', '/var/www/nginx-cache/');
    volumes:
      - wordpress_html:/var/www/html:rw
      #- nginx_cache:/var/www/nginx-cache:rw
    container_name: wordpress
    networks:
      - nginx-network

  wp-cli:
    image: wordpress:cli
    user: "33"
    volumes:
      - wordpress_html:/var/www/html
    container_name: wp-cli
    env_file:
      - ./wordpress/wordpress.env
    command: wp core download --path="/var/www/html" --version=latest
    networks:
      - nginx-network
    depends_on:
      - wordpress

  nginx:
    image: nginx:1.21.0-alpine
    depends_on:
      - wordpress
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - wordpress_html:/var/www/html:rw
      - nginx_cache:/var/run/nginx-cache:rw
      #- type: bind
        #source: ./wordpress/html
        #target: /var/www/html
      - type: bind
        source: ./nginx/nginx-conf
        target: /etc/nginx/conf.d
      #- type: bind
        #source: ./nginx/cache
        #target: /var/run/nginx-cache
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge

volumes:
  wordpress_html:
    name: wordpress_html
    external: true
  nginx_cache:
    name: nginx_cache
    external: true

